(defun main ()
(let ((a (read))
    (b (read))
    (c (read))
    (d (read)))
    (setq a (/ b a))
    (setq c (/ d c))
    (if (= a c)
        (format t "DRAW~%")
        (if (> a c)
            (format t "TAKAHASHI~%")
            (format t "AOKI~%")))))
(main)