(defun main ()
  (setf a (read))
  (setf b (read))
  (setf c (read))
  (setf k (read))
  (setf s (read))
  (setf u (read))
  (if (<= k (+ s u)) (princ (-(+ (* a s) (* b u)) (* (+ s u) c))) (princ (+ (* a s) (* b u))))
  (fresh-line))
(main)
